### ISSUE TITLE
Support for Typecho blogging platform

### ISSUE THREAD

**Issue by adamqqqplay** [LetTTGACO/elog#75]
### 你当前使用的Elog版本

v0.13.3

### 描述一下此特性

Hello Elog developers, I am very happy to find such an excellent project that makes it easier for everyone to write blogs. However, I found that this project currently does not support publishing articles to typecho, a popular blogging platform.

[Typecho](https://typecho.org/) is a lightweight blogging platform similar to wordpress. It has a complete [documentation](https://docs.typecho.org/) and plug-in mechanism and should be well connected with the elog project. 

I hope to add new features in elog to output markdown documents to the typecho blog. Thanks in advance!

**Comment by LetTTGACO** [comment]
Thank you very much for your suggestion. Since Elog is a program implemented in node, it needs a set of Restful api to interact with typecho. But as I read the documentation of typecho and the plugin mechanism, it looks like it doesn't provide a direct api interface for md documents to be uploaded to the blog site, but rather a plugin mechanism for developers to expose the relevant Restful api interfaces outwardly.

But I can't find any plugin that exposes APIs for uploading documents/images etc. I found the following plugin that exposes part of typecho's APIs, but its readme doesn't seem to have any related post interfaces.
- https://github.com/st1ven/typecho-api
- https://github.com/moefront/typecho-plugin-Restful

If you want to use Elog to synchronize documents to typecho blog, there are several prerequisites
1. find the relevant typecho plugin that exposes the complete api for Elog to call
2. if you don't find a plugin that meets the criteria, you need to implement the typecho plugin yourself, but I'm not good at PHP at the moment, so I may need help from the Elog community or the typecho community to implement the relevant plugin.
3. Elog is currently undergoing refactoring to prepare for the future version 1.0, which is expected to be released in beta at the end of April and in full version at the end of May. If the typecho plugin is ready, Elog will be adapted in the 1.x version!

If you find a typecho plugin that matches Elog's calls, I'll put adapting typecho on the agenda. Until then, Elog has no plans to adapt typecho.

Finally, thanks again for your use and suggestions!

-------------------------------------------------------------------------------------------------------------------

非常感谢你的建议。因为 Elog 是用 node 实现的程序，它需要一套Restful api来和typecho进行交互。但我看了 typecho 的文档以及插件机制，它看起来并没有直接提供 api 接口让 md 文档上传到博客站点，而是提供了插件机制，让开发者向外暴露相关的 Restful api 接口。

但我暂时没找到相关的插件向外暴露上传文档/图片等 API，我找到以下插件暴露了typecho 的部分 API，但它的readme 文档貌似没有找到 相关的 post 接口
- https://github.com/st1ven/typecho-api
- https://github.com/moefront/typecho-plugin-Restful

如果要实现 使用 Elog 同步文档到typecho 博客，有以下几个前提
1. 找到相关 typecho 的插件，暴露完整的 api 供 Elog 调用
2. 如果没有找到符合条件的插件，就需要自己实现typecho 的插件，但我目前并不擅长 PHP，可能需要 Elog 社区或typecho 社区帮忙实现相关插件
3. Elog 目前正在进行重构工作，为未来的 1.0 版本做准备，1.0 版本预计在4月底发布 beta 版本，5 月底发布正式版。如果typecho插件准备完毕，Elog 将在 1.x 版本进行适配

如果你有找到符合 Elog 调用的 typecho 插件，我会把适配typecho提上日程。在这之前，Elog 并没有计划适配typecho。

最后，再次感谢你的使用和建议！
